#! /bin/sh

pidof bspswallow || bspswallow &
sxhkd &
killall -q polybar;polybar example &
#nitrogen --restore &
xautolock -time 10 -locker "i3lock -i /home/shyciii/Pictures/captain-americby.png" &
udiskie &

bspc monitor -d 1 2 3 4 5

bspc config border_width        3
bspc config window_gap          5
bspc config focused_border_color "#c93648"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule --add Gimp-2.10 state=floating
#bspc rule --add Gpicview state=fullscreen
bspc rule --add st-256color:st_vifm_help state=floating rectangle=800x500+560+290
bspc rule --add st-256color:help state=floating center=on
bspc rule --add Gcr-prompter focus=on
#bspc rule --add Chromium desktop=2
bspc rule --add Transmission-gtk desktop=4 follow=on
bspc rule --add xfreerdp state=tiled desktop=3 follow=on
#bspc rule --add mpv focus=on
#bspc rule --add Kupfer.py focus=on
